#Login Page Elements
txt_loginUsername="name:userName"
txt_loginPassword="name=password"
btn_signIn="xpath://input[@name='submit']"

#Registrar Page Element
link_Reg="link:REGISTER"
txt_firstName="name:firstName"
txt_lastName="name:lastName"
txt_phone="name:phone"
txt_email="name:userName"
txt_add1="name:address1"
txt_city="name:city"
txt_state="name:state"
txt_postalCode="name:postalCode"
drp_country="name:country"
txt_userName="name:email"
txt_password="name:password"
txt_confirmPassword="name:confirmPassword"
btn_submit="xpath://input[@name='submit']"
